"""Initial schema setup

Revision ID: 0235f9f5fbea
Revises: 
Create Date: 2026-09-25 10:37:46.790004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0235f9f5fbea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('savesage_bank_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_name'), 'banks', ['name'], unique=False)
    op.create_index(op.f('ix_banks_savesage_bank_id'), 'banks', ['savesage_bank_id'], unique=False)
    op.create_index(op.f('ix_banks_slug'), 'banks', ['slug'], unique=True)
    op.create_table('spend_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('savesage_category_id', sa.Integer(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_categories_savesage_category_id'), 'spend_categories', ['savesage_category_id'], unique=False)
    op.create_index(op.f('ix_spend_categories_slug'), 'spend_categories', ['slug'], unique=True)
    op.create_table('sync_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cards_fetched', sa.Integer(), nullable=False),
    sa.Column('tabs_fetched', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('joining_fee', sa.Float(), nullable=False),
    sa.Column('renewal_fee', sa.Float(), nullable=False),
    sa.Column('forex_markup_percent', sa.Float(), nullable=True),
    sa.Column('apr_percent', sa.Float(), nullable=True),
    sa.Column('add_on_card_fee', sa.Float(), nullable=True),
    sa.Column('return_percentage_raw', sa.String(length=100), nullable=True),
    sa.Column('return_min_percent', sa.Float(), nullable=False),
    sa.Column('return_max_percent', sa.Float(), nullable=False),
    sa.Column('network_type', sa.String(length=50), nullable=True),
    sa.Column('lounge_types', sa.JSON(), nullable=False),
    sa.Column('benefit_types', sa.JSON(), nullable=False),
    sa.Column('category_slugs', sa.JSON(), nullable=False),
    sa.Column('is_fd_card', sa.Boolean(), nullable=False),
    sa.Column('is_business_card', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_currently_issuing', sa.Boolean(), nullable=False),
    sa.Column('web_logo_url', sa.String(length=500), nullable=True),
    sa.Column('card_image_url', sa.String(length=500), nullable=True),
    sa.Column('apply_link', sa.String(length=1000), nullable=True),
    sa.Column('overview_text', sa.Text(), nullable=True),
    sa.Column('best_suited', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_bank_id'), 'credit_cards', ['bank_id'], unique=False)
    op.create_index(op.f('ix_credit_cards_is_business_card'), 'credit_cards', ['is_business_card'], unique=False)
    op.create_index(op.f('ix_credit_cards_is_currently_issuing'), 'credit_cards', ['is_currently_issuing'], unique=False)
    op.create_index(op.f('ix_credit_cards_is_fd_card'), 'credit_cards', ['is_fd_card'], unique=False)
    op.create_index(op.f('ix_credit_cards_is_popular'), 'credit_cards', ['is_popular'], unique=False)
    op.create_index(op.f('ix_credit_cards_joining_fee'), 'credit_cards', ['joining_fee'], unique=False)
    op.create_index(op.f('ix_credit_cards_network_type'), 'credit_cards', ['network_type'], unique=False)
    op.create_index(op.f('ix_credit_cards_renewal_fee'), 'credit_cards', ['renewal_fee'], unique=False)
    op.create_index(op.f('ix_credit_cards_return_max_percent'), 'credit_cards', ['return_max_percent'], unique=False)
    op.create_index(op.f('ix_credit_cards_return_min_percent'), 'credit_cards', ['return_min_percent'], unique=False)
    op.create_index(op.f('ix_credit_cards_slug'), 'credit_cards', ['slug'], unique=True)
    op.create_index(op.f('ix_credit_cards_title'), 'credit_cards', ['title'], unique=False)
    op.create_table('card_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=50), nullable=False),
    sa.Column('raw_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'tab_name', name='uq_card_tab')
    )
    op.create_index(op.f('ix_card_tabs_card_id'), 'card_tabs', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_tabs_tab_name'), 'card_tabs', ['tab_name'], unique=False)
    op.create_table('user_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('last_4_digits', sa.String(length=4), nullable=True),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'nickname', name='uq_user_card_instance')
    )
    op.create_index(op.f('ix_user_cards_card_id'), 'user_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_cards_user_id'), 'user_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cards_user_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_card_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_card_tabs_tab_name'), table_name='card_tabs')
    op.drop_index(op.f('ix_card_tabs_card_id'), table_name='card_tabs')
    op.drop_table('card_tabs')
    op.drop_index(op.f('ix_credit_cards_title'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_slug'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_return_min_percent'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_return_max_percent'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_renewal_fee'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_network_type'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_joining_fee'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_is_popular'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_is_fd_card'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_is_currently_issuing'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_is_business_card'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_bank_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sync_audit_logs')
    op.drop_index(op.f('ix_spend_categories_slug'), table_name='spend_categories')
    op.drop_index(op.f('ix_spend_categories_savesage_category_id'), table_name='spend_categories')
    op.drop_table('spend_categories')
    op.drop_index(op.f('ix_banks_slug'), table_name='banks')
    op.drop_index(op.f('ix_banks_savesage_bank_id'), table_name='banks')
    op.drop_index(op.f('ix_banks_name'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
