"""add_wallet_catalog_device_token_features

Revision ID: 8db00fd75200
Revises: 0235f9f5fbea
Create Date: 2026-09-26 11:53:17.717016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db00fd75200'
down_revision: Union[str, None] = '0235f9f5fbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.add_column('credit_cards', sa.Column('fee_waiver_spend', sa.Float(), nullable=True))
    op.add_column('credit_cards', sa.Column('point_value_inr', sa.Float(), nullable=True))
    op.add_column('user_cards', sa.Column('statement_day', sa.Integer(), nullable=True))
    op.add_column('user_cards', sa.Column('due_day', sa.Integer(), nullable=True))
    op.add_column('user_cards', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cards', 'sort_order')
    op.drop_column('user_cards', 'due_day')
    op.drop_column('user_cards', 'statement_day')
    op.drop_column('credit_cards', 'point_value_inr')
    op.drop_column('credit_cards', 'fee_waiver_spend')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
